### PR TITLE
itsmekori/eng-616-update-links

### PR DESCRIPTION
**Pull request by IvySwing**

### CODE REVIEW

**Review by stormcloud266 — CHANGES_REQUESTED** [review]
We'll want to use the named routes like [this example](https://redwoodjs.com/docs/router#link-and-named-route-functions), however those routes aren't in the redwood branch yet. They're in the PR we're working in right now, so let's put this PR on hold until we get the correct routes merged in. Also, feel free to delete the comments with the old code, we can always look up the old stuff if we need to.

**Comment by IvySwing** [comment]
@stormcloud266 Are you referring to the comments about the "todo" and the import of lib/constants?

**Comment by stormcloud266** [comment]
@IvySwing It looks like the old buttons were commented out, and the new buttons are below them. Those comments with the old buttons can go

**Comment by IvySwing** [comment]
@stormcloud266 the old buttons have been removed

**Comment by stormcloud266** [comment]
All the info needed for this to be updated is in the redwood branch now

**Pull request closed without merging**
