### PR TITLE
patch no nft wallet connect fix

### PR DESCRIPTION
**Pull request by ham-evans**

### CODE REVIEW

**Review by chair28980 — APPROVED** [review]
LGTM 🍏

**Comment by stormcloud266** [comment]
This looks like it says 'save NFT to your profile' even though there wouldn't be an NFT to save. But also, I'm wondering what the desired functionality would be after they solve a puzzle with no NFT @chair28980 . Their only option is to send in their email?

**Comment by chair28980** [comment]
> 

You are correct, if there is no NFT we can display a "Congrats you did it" message similar to what we did with the old message signing flow.

We need to add a button/link back to the puzzles in that view.

cc @ham-evans

**Comment by chair28980** [comment]
@ham-evans can we have the button say "submit" if there is no NFT

submit-button

**Review by chair28980 — APPROVED** [review]
LGTM 🍏

**Pull request merged**
