### PR TITLE
add discord icon & set up hover/fill on both icons

### PR DESCRIPTION
**Pull request by IvySwing**

### CODE REVIEW

**Comment by IvySwing** [comment]
@chair28980 how does the spacing look between the input field and icons?

**Comment by chair28980** [comment]
Screen Shot 2022-09-01 at 5 03 09 PM

@IvySwing looks right to me

**Comment by chair28980** [comment]
Small note, lets keep the "Start looking for keys" text on the page.

**Review by chair28980 — APPROVED** [review]
LGTM 🍏

**Pull request merged**
