### PR TITLE
ENG-548 Puzzle UI

### PR DESCRIPTION
**Pull request by stormcloud266**

### CODE REVIEW

**Comment by chair28980** [comment]
Screenshot 2022-12-13 at 8 44 55 PM

@stormcloud266 getting the above error when running this branch locally

**Comment by stormcloud266** [comment]
@chair28980 I'll investigate

**Comment by chair28980** [comment]
@stormcloud266 UI looking EXCELLENT here, will defer to @illepic for code sign off.

**Review by chair28980 — APPROVED** [review]
LGTM 🍏

**Pull request merged**
