### PR TITLE
created new newsletter email form and updated business email form

### PR DESCRIPTION
**Pull request by IvySwing**

### CODE REVIEW

**Comment by chair28980** [comment]
@IvySwing Looking good! Please take a look at and update the failing test.

**Comment by IvySwing** [comment]
@chair28980 @illepic @stormcloud266 All checks have passed. I need at least one person to approve in order for me to merge.

**Comment by chair28980** [comment]
@IvySwing approval coming up!

**Review by chair28980 — APPROVED** [review]
LGTM 🍏

**Review by stormcloud266 — APPROVED** [review]

**Pull request merged**
