### PR TITLE
update success message on solved page

### PR DESCRIPTION
**Pull request by IvySwing**

### CODE REVIEW

**Comment by IvySwing** [comment]
@illepic @chair28980 @stormcloud266 In going over the logic with Tawnee, we were wondering about the necessity of most of the code found in wallet-email.tsx.  I haven't worked on the logic for the wallet connect but Tawnee said it appears that we don't use most of the logic there since we have the global wallet connect. Thoughts?

**Comment by IvySwing** [comment]
> @illepic @chair28980 @stormcloud266 In going over the logic with Tawnee, we were wondering about the necessity of most of the code found in wallet-email.tsx. I haven't worked on the logic for the wallet connect but Tawnee said it appears that we don't use most of the logic there since we have the global wallet connect. Thoughts?

Update: I spoke to Ham and the work I've done won't impact the cleanup he's doing right now.  However, once my work is merged and his completed work is merged, we should have a discussion on the next level of refactoring that may need to be done.

**Review by chair28980 — CHANGES_REQUESTED** [review]
@IvySwing  when I solve the the notright puzzle, the text in the success message looks correct. However on the other puzzles im testing, the success message still displays in the old info box style.

communitycode:
Screen Shot 2022-09-02 at 1 32 33 PM

gram:
Screen Shot 2022-09-02 at 1 33 19 PM

Please ensure the success message for all the puzzles displays with the updated style.

**Review by chair28980 — APPROVED** [review]
I retract my previous comment!

Tested on puzzles with custom success_message and LGTM! 🍏

**Pull request merged**
