### PR TITLE
add socials to packs show view

### PR DESCRIPTION
**Pull request by IvySwing**

### CODE REVIEW

**Review by chair28980 — CHANGES_REQUESTED** [review]
Looking good! One smol note, can you have the discord icon turn purple on hover, same as the footer?

**Comment by IvySwing** [comment]
> Looking good! One smol note, can you have the discord icon turn purple on hover, same as the footer?

It's done! Should I have the twitter icon match?

**Comment by chair28980** [comment]
> > Looking good! One smol note, can you have the discord icon turn purple on hover, same as the footer?
> 
> It's done! Should I have the twitter icon match?

Yeah that sounds comfy!

**Review by chair28980 — APPROVED** [review]
LGTM! 🍏

**Pull request merged**
